#!/bin/bash

if [[ -z "$TEXT_EDITOR" ]]; then
	echo "Envrionment variable TEXT_EDITOR is not set. Please add a perferred editor to your environment variable."

	exit 1
else
	EDITOR="$TEXT_EDITOR"
fi

THRESHOLD=5
ROOT_DIR=$(git rev-parse --show-toplevel)
SEARCH=""
CHANGES=$(git status --porcelain)

if [[ ! -z "$1" ]] ; then
	SEARCH="$1"
fi

FILE_COUNT=$(git status --porcelain | grep "$SEARCH" | awk '{print $2}' | wc -l)

if [[ "$FILE_COUNT" -eq 0 ]] ; then
	echo "No files found. Did you grep correctly?"

	exit 1
fi

openFiles() {
	cd "$ROOT_DIR" &&
	git status --porcelain | grep "$SEARCH" | awk '{print $2}' | xargs "$EDITOR"
}

if [[ "$FILE_COUNT" -ge "$THRESHOLD" ]] ; then
	# Prompt for confirmation
	echo "$CHANGES" | grep "$SEARCH"
	read -rsn 1 -p "You are about to open $FILE_COUNT files with your editor \"$EDITOR\". [Type \"Y\" to confirm]: " CONFIRM

	if [ "$CONFIRM" == "Y" ] ; then
		openFiles
	else
		echo "Canceled opening files."

		exit 1
	fi
else
	openFiles
fi