#!/bin/bash

workspace="4:   "

i3-msg "workspace $workspace; append_layout /home/joshua/configs/layouts/comms.json"

i3-msg "workspace $workspace; exec discord;"
i3-msg "workspace $workspace; exec spotify;"
i3-msg "workspace $workspace; exec franz;"
