#!/bin/bash

workspace="2:   "

i3-msg "workspace $workspace; append_layout /home/joshua/configs/layouts/dev.json"

i3-msg "workspace $workspace; exec subl;"
i3-msg "workspace $workspace; exec alacritty;"
i3-msg "workspace $workspace; exec alacritty"
i3-msg "workspace $workspace; exec alacritty;"
