#!/bin/env bash

# Reload custom environment variables
source ~/.envs

# Colors used for console logging
ENDC="\033[0m"
RED="\033[91m"
YELLOW="\033[33m"
PURPLE="\033[95m"
OKGREEN="\033[92m"

ERROR="$RED[ERROR]$ENDC"

# Exit point
quit_script() {
  echo -e "$YELLOW\nExiting."
  kill -INT $$
}

# Check for machine descriptor environment variable
if [[ -z "$MACHINE_NAME" ]]
then
  echo -e "$ERROR This start-up script requires the environment variable $YELLOW\"MACHINE_NAME\"$ENDC to be set before this will run. \nAdd this environment variable to your $YELLOW\".envs\"$ENDC in your home directory."
  quit_script
fi

# Check for network environment variable
if [[ -z "$WIRELESS_NETWORK" && -z "$WIRED_NETWORK" ]]
then
  echo -e "$ERROR This start-up script requires the environment variable $YELLOW\"WIRELESS_NETWORK\"$ENDC or $YELLOW\"WIRED_NETWORK\"$ENDC to be set before this will run. \nAdd this environment variable to your $YELLOW\".envs\"$ENDC in your home directory."
  quit_script
fi

# Check for monitor name environment variable
if [[ -z "$MONITOR_NAME" ]]
then
  echo -e "$ERROR This start-up script requires the environment variable $YELLOW\"MONITOR_NAME\"$ENDC to be set before this will run. \nAdd this environment variable to your $YELLOW\".envs\"$ENDC in your home directory."
  quit_script
fi

# Check for github auth token
if [[ -z "$TOKEN_GITHUB" ]]
then
  echo -e "$ERROR This start-up script requires the environment variable $YELLOW\"TOKEN_GITHUB\"$ENDC to be set before this will run. \nAdd this environment variable to your $YELLOW\".envs\"$ENDC in your home directory."
  quit_script
fi

# Determine what scripts to run based on the machine name provided.
start() {
  export BAR_WLAN="$WIRELESS_NETWORK"
  export GITHUB_TOKEN="$TOKEN_GITHUB"
  export MONITOR="$MONITOR_NAME"

  case "$MACHINE_NAME" in
    "PERSONAL"*)
      echo -e "Establishing personal machine settings."

      dev
    ;;
    "WORK"*)
      echo -e "Establishing work machine settings."

      dev &&
      comms
    ;;
    *)
      echo -e "Machine_NAME not recognized. Ensure your enviornment variables are set correctly"
    ;;
  esac

}

start
