#!/bin/env bash

ENDC="\033[0m"
RED="\033[91m"
YELLOW="\033[33m"
PURPLE="\033[95m"
OKGREEN="\033[92m"

ERROR="$RED[ERROR]$ENDC"


# Reload custom environment variables.
source ~/.envs

# Exit
quit_script() {
  echo -e "$YELLOW\nExiting."
  kill -INT $$
}

# Check for machine descriptor environment variable
if [[ -z "$MACHINE" ]]
then
  echo -e "$ERROR This start-up script requires the environment variable $YELLOW\"MACHINE\"$ENDC to be set before this will run. \nAdd this environment variable to your $YELLOW\".envs\"$ENDC in your home directory."
  quit_script
fi

# Check for network environment variable
if [[ -z "$WIRELESSNETWORK" && -z "$WIREDNETWORK" ]]
then
  echo -e "$ERROR This start-up script requires the environment variable $YELLOW\"WIRELESSNETWORK\"$ENDC or $YELLOW\"WIREDNETWORK\"$ENDC to be set before this will run. \nAdd this environment variable to your $YELLOW\".envs\"$ENDC in your home directory."
  quit_script
fi

# Check for monitor name environment variable
if [[ -z "$MONITORNAME" ]]
then
  echo -e "$ERROR This start-up script requires the environment variable $YELLOW\"MONITORNAME\"$ENDC to be set before this will run. \nAdd this environment variable to your $YELLOW\".envs\"$ENDC in your home directory."
  quit_script
fi

# Check for github auth token
if [[ -z "$TOKEN_GITHUB" ]]
then
  echo -e "$ERROR This start-up script requires the environment variable $YELLOW\"TOKEN_GITHUB\"$ENDC to be set before this will run. \nAdd this environment variable to your $YELLOW\".envs\"$ENDC in your home directory."
  quit_script
fi

# Determine what scripts to run based on the machine name provided.
case "$MACHINE" in
  "PERSONAL"*)
    echo -e "Establishing personal machine settings."
    export BAR_WLAN="$WIRELESSNETWORK"
    export GITHUB_TOKEN="$TOKEN_GITHUB"

  ;;
  "WORK"*)
    echo -e "Establishing work machine settings."

  ;;
  *)
    echo -e "Machine not recognized. Ensure your enviornment variables are set correctly"
  ;;
esac




# If work machine
  # Set monitor
  # Start polybar on work monitor
  # set environment variables for polybar network
  # dev & comms

# If personal
  # Set polybar to main screen
  # set env varible for polybar wifi network






